### ISSUE TITLE
¿Cómo se pretende de gestionar las devoluciones?

### ISSUE THREAD

**Issue by antoniorr02** [giorgiogiovanni/PacketManager#10]
En #3 se habla de un transportista. ¿Es necesario definir lo que es un transportista o nos vale con reutilizar el concepto de encargado?

**Comment by JJ** [comment]
¿Qué problema se plantea aquí, aparte de una pregunta?

**Comment by antoniorr02** [comment]
Se plantea la problematica de tener que definir que es una devolución y los participantes asociados a la misma.

**Comment by JJ** [comment]
El título habla de devoluciones. El cuerpo de transportista. Hace referencia a #3. ¿Ya se ha definido todo lo necesario para #2?

**Comment by antoniorr02** [comment]
Sí, para la HU1 no se hace referencia a las devoluciones, sin embargo, #3 está asociado al milestone 0, con lo que consideré necesaria la implementación para el desarrollo del modelo.

**Comment by JJ** [comment]
Como persona que desarrolla, tendrás que priorizar, ¿no?

**Comment by antoniorr02** [comment]
Como desarrollador he priorizado la documentación del objetivo 2, que indica lo siguiente: 

"...implementar las historias de usuario existentes, evidentemente avanzando las historias de usuario que se hayan creado en el primer hito en la secuencia, al menos las que estén relacionadas con el milestone en el que se esté trabajando."

Con ello he realizado el modelado de lo relativo al milestone 0.
